---
version: 0.1.15
files:
  README.md:
  - long-dream-core v%.%.%
  - doc/v%.%.%
  bower.json:
  - '"version": "%.%.%"'
  package.json:
  - '"version": "%.%.%"'
  ".jsduck.release.json":
  - "(v%.%.%)"
  - doc/v%.%.%
